
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app1-00
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: 
  destination: 
    namespace: dcp
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook
    repoURL: "https://github.com/ppngiap/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
  automated:
    prune: true
    selfHeal: true
    syncOptions:
      - CreateNamespace=true
