apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app1-subdir
  namespace: argocd
spec: 
  destination: 
    namespace: app1-subdir
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook
    repoURL: "https://github.com/ppngiap/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
