
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app5-03
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec: 
  destination: 
    namespace: app5-03 
    server: "https://kubernetes.default.svc"
  project: dcp
  source: 
    path: guestbook
    repoURL: "https://github.com/ppngiap/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
